### ISSUE TITLE
Scenario Zero code error

### ISSUE THREAD

**Issue by aliasadi2001** [wineslab/ns-o-ran-ns3-mmwave#11]
![Screenshot 2024-02-07 145720](https://github.com/wineslab/ns-o-ran-ns3-mmwave/assets/137979233/656a0be8-4bb8-465c-9e17-e1bf8bbd9f3b)
hello 
I want to run Scenario Zero code in ns-ORAN but I am getting this error.
Can anybody help me to fix this issue? 

Thank You.

**Comment by DrizzlingVoid** [comment]
Hi, 

Same error for myself, with some more detail in attached as screenshots. 

System info: Ubuntu 22.x and Ubuntu 23.x.

All installation steps completed following this tutorial: [https://openrangym.com/tutorials/ns-o-ran](https://openrangym.com/tutorials/ns-o-ran). g++-9 was used to compile ns-3 with Waf due to compatibility issues.

Confirmation of Docker running with all images properly pulled and operating and screenshots of all relevant terminals are as follows.

1. Terminal running the sample xApp:
![Screenshot_4](https://github.com/wineslab/ns-o-ran-ns3-mmwave/assets/15089063/50d30ece-f2ab-4e3d-8a62-e63f1ee56bfb)

2. "2nd Terminal" to log the E2Term:
![Screenshot_3](https://github.com/wineslab/ns-o-ran-ns3-mmwave/assets/15089063/a1022413-231e-49a2-a7e6-33357a460540)

3. Main terminal for ns-3 simulation with Docker image checked:
![Screenshot_1](https://github.com/wineslab/ns-o-ran-ns3-mmwave/assets/15089063/9dde08a0-17dc-402c-936f-b608f3642d7c)


By the way, it is possible to know whether updating to a newer version of ns-3 with Cmake is on schedule, and if so, is there a timeline available? 

Many thanks and look forward to your reply.


Best regards,
KT

**Comment by Thecave3** [comment]
Hi, I will check these errors and let you know.

**Comment by Thecave3** [comment]
I believe this is an issue with the `contrib` module. The double `free` operation is in /model/asn1c-types.cc#L882-L883.
Please try to comment it and let me know if this solves the issue

The new version of ns-3 mmwave o-ran compliant is expected for Q2 2024.

**Comment by aliasadi2001** [comment]
Can you describe it in more detail, please?
this is the screenshot of the lines in the asn1c-type.cc
these lines only include a "}" character.
I am getting syntax errors while I comment the two lines.

![image](https://github.com/wineslab/ns-o-ran-ns3-mmwave/assets/137979233/4e6102c9-c6ac-4b56-a743-1c0d7bddd854)

**Comment by Thecave3** [comment]
Sorry for the imprecision, you can comment safely lines 880 and 881.

**Comment by Thecave3** [comment]
I am not able to reproduce your error, I might need more context about the issue. Can you run ns-3 with gdb (`--ggbd` flag) and check the stacktrace?

Are you using the docker container for ns-3?

**Comment by aliasadi2001** [comment]
Hi 
thank you for your help
this is running scenario-zero. cc with --gdb flag backtrace.

![image](https://github.com/wineslab/ns-o-ran-ns3-mmwave/assets/137979233/2041d19c-33e3-472d-8f57-5f07c2715e48)

I installed the 3.36 version of ns3 separately and used this [website](https://openrangym.com/tutorials/ns-o-ran)  for all implementations.

but it seems the mm Wave ns3 is not dockerized and uses waf build system.

all the other sections like( xApp container and etc) are working correctly.

best regards,

**Comment by Thecave3** [comment]
Okay, does this error persist with the ns-3 docker container? At the moment we do not fully support ubuntu 22

**Comment by DrizzlingVoid** [comment]
Hi,

> From the official tutorial:
> > To properly install ns-3 and ns-O-RAN, several options are available, including using the Dockerfile provided in the root of the near-RT RIC repository.
> Can you try using the docker container and check if this error persists?

Could you please specify? If this repository refers to [this one](https://github.com/wineslab/colosseum-near-rt-ric?tab=readme-ov-file), I'm having problem finding this Docker container. There isn't any mention of such setup to follow in the [original tutorial](https://openrangym.com/tutorials/ns-o-ran) where this quote comes from either, making it very hard to make further actions.


> At the moment we do not fully support ubuntu 22 and the updated g++ version.

Does this also mean installing ns-o-ran locally on an older version, e.g. Ubuntu 20, might work?


Many thanks to your patience.

**Comment by aliasadi2001** [comment]
Thank you for your guides
I implemented it from zero in Ubuntu 20.04 and it is working correctly now.
it seems it is not compatible with Ubuntu 22.

but I have one question
this screenshot is the xApp terminal tab that working correctly.
![image](https://github.com/wineslab/ns-o-ran-ns3-mmwave/assets/137979233/9a0b20e4-e98c-49bf-a70c-be58f3d45f17)

and this is the e2term tab that is working now.
![image](https://github.com/wineslab/ns-o-ran-ns3-mmwave/assets/137979233/29130dae-952b-4f7e-8bb1-a1436d08c84c)

but my ns-Oran tab interrupted after running and connecting according to this screenshot.

![image](https://github.com/wineslab/ns-o-ran-ns3-mmwave/assets/137979233/19484d36-ce84-49f0-be1b-61fdca2784c5)

Is it ok?
Does this interruption cause a problem?

**Comment by Thecave3** [comment]
Glad that helped. I believe your terminal is scrolling very fast, but if the indication messages are delivered correctly to the xApp it is fine.

For future visitors that may come here: the `waf` version of ns-3 does not support newer versions of Ubuntu. Please use Ubuntu 20.04 or the Dockerfile [here](https://github.com/wineslab/colosseum-near-rt-ric/blob/ns-o-ran/Dockerfile)
