### ISSUE TITLE
NS3, E2, RIC, and Xapp Messaging

### ISSUE THREAD

**Issue by alysabry** [wineslab/ns-o-ran-ns3-mmwave#2]
I want to know if it is possible to send my own design message not an E2AP_PDU message from NS3 to your sample xapp?

I believe the messaging from the NS3 to the RIC over the E2 interface is carried over through the socket using this SendE2Message function, right? and the message needs to be received at the RIC first then retransmitted to the xapp using this function send_socket.
 So, how does the RIC itself receive the message from the E2, is it must be an rmr and must be received using this rmr_rcv_msg function to be received correctly and processed or is there a socket receiver at the RIC to get it from the E2 interface because I could not find it? 

If the only messages that can be transferred are the RMR, the received RMR messages on the RIC is kind of weird and it is a bit of encoded in a different way how the one can retrieve the same numbers transmitted from the NS3?

**Comment by Thecave3** [comment]
Hi @alysabry ,

> I want to know if it is possible to send my own design message not an E2AP_PDU message from NS3 to your sample xapp?

You can customize the content of the E2SM, since its definition is shared between the xApp and the RAN (check the [original branch of the RIC](https://github.com/wineslab/colosseum-near-rt-ric), here we use as E2SM strings instead of ASN1c encoded data).


> I believe the messaging from the NS3 to the RIC over the E2 interface is carried over through the socket using this SendE2Message function, right?

Yes, in NS-3, but after this step, the E2AP PDU is handled by the RAN E2Term (with E2sim) and sent to the RIC E2 Termination using the SCTP socket.
[This ](https://github.com/wineslab/colosseum-near-rt-ric/blob/a8702a399a6b33ac383e387f8be274fcad5d9292/setup/e2/RIC-E2-TERMINATION/sctpThread.cpp#L1147) should be the receive function on the RIC, but I am not 100% sure since this code was inherited from the Col-O-RAN RIC.
